id: I7C7CC446
ocr_import_info:
  bdrc_scan_id: W3CN7561
  source: bdrc
  ocr_info:
    timestamp: '2022-08-25T00:00:00Z'
  batch_id: batch-0001
  software_id: norbuketaka
  expected_default_language: bo
  op_import_options: null
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-01-21 16:36:28.102824
last_modified: 2022-08-25 00:00:00+00:00
parser: https://github.com/OpenPecha/Norbu-Keta-eText-import/blob/main/norbu_ketaka_parser.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN7561
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN7561
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གྲུབ་ཆེན་ཐང་སྟོང་རྒྱལ་པོ་དང་འབྲེལ་བའི་བླ་མའི་རྣལ་འབྱོར།
  languages:
  - bo
bases:
  I3CN7563:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7563
      total_pages: 42
      volume_number: 1
      volume_pages_bdrc_intro: 2
    base_file: I3CN7563.txt
    order: 1
copyright:
  status: Public domain
  notice: The proofread texts are donated by the Norbu Ketaka project led by Queenie
    Luo (Harvard University), Zhiying Li (Sichuan University) and Leonard van der
    Kuijp (Harvard University). Correspondence should be directed to  queenieluo@g.harvard.edu
license: CC0
